---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oetp-controller-role
  namespace: {{ $.Release.Namespace }}
  labels:
    {{ template "oetp.common-labels" . }}
rules:
  {{- range $resource := .Values.resourcesToCreate }}
  - apiGroups:
      - "{{ $resource.apiGroup }}"
    resources:
      - "{{ $resource.resource }}"
    verbs:
      - "create"
  {{ end }}
  - apiGroups:
      - "ticq.io"
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - "k8s.ovn.org"
    resources:
      - "EgressFirewall"
    verbs:
      - "*"