image:
  registry: "ghcr.io"
  repository: "gijsvandulmen/openshift-egress-tenant-policies"
  tag: "1.0"

  pullPolicy: Always

logLevel: "INFO"

resourcesToCreate: []

resources:
  limits:
    memory: 300Mi
    cpu: 500m
  requests:
    memory: 50Mi
    cpu: 100m