apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: egresspolicies.ticq.dev
spec:
  group: ticq.dev
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                groups:
                  type: array
                  items:
                    type: string
                egress:
                  type: array
                  items:
                    type: object
                    required: [ "type" ]
                    oneOf:
                      - required: [ "dnsName" ]
                      - required: [ "cidr" ]
                      - required: [ "group" ]
                    properties:
                      type:
                        type: string
                        enum: [ "Allow", "Deny" ]
                      dnsName:
                        type: string
                      cidr:
                        type: string
  names:
    kind: EgressPolicy
    plural: egresspolicies
  scope: Namespaced
